### ISSUE TITLE
/logout does not work

### ISSUE THREAD

**Issue by jzkunlun** [pouchdb/pouchbase#45]
call /logout, it return 'bad request 400'  
Error: invalid json
    at parse (/home/dir/pouch.host/node_modules/body-parser/lib/types/json.js:72:15)
    at /home/dir/pouch.host/node_modules/body-parser/lib/read.js:98:18
    at IncomingMessage.onEnd (/home/dir/pouch.host/node_modules/body-parser/node_modules/raw-body/index.js:136:7)
    at IncomingMessage.g (events.js:175:14)
    at IncomingMessage.EventEmitter.emit (events.js:92:17)
    at _stream_readable.js:920:16

**Comment by BigBlueHat** [comment]
I believe you can use a custom protocol handler in a separate link in the email to load in an app.

Something like: `my-pouch-app://{in-app-registration-url}/{token}`

The app (afaik) gets that entire string, and can do what it wants with it.

I've not personally done this, so your mileage may vary. :blue_car:
